### ISSUE TITLE
Git history is off

### ISSUE THREAD

**Issue by mpscholten** [gitpod-io/template-ihp#2]
I was just testing the new template and somehow it was not working. 

The init script uses the following code:

```bash
git remote add ihp https://github.com/digitallyinduced/ihp-boilerplate.git
git pull ihp gitpod --rebase
```

This is used to fetch the latest IHP project boilerplate into the project (this is similiar to running `ihp-new` when doing development locally).

This was working perfectly fine in the old repo. In this new repo, the boilerplate is not there when a new gitpod is started.

I debugged this a little bit. Git always returned `Already up to date`. After a couple minutes I figured out: This repo has 160 commits right now:

![image](https://user-images.githubusercontent.com/2072185/132811688-98375257-6aa8-4f1d-b2bd-32dfb8bfc063.png)

If you look at the git history you can see that this repo somehow contains all the commits of the boilerplate :) So something went wrong while setting it up.

@ghuntley can you rebase this repo so that only the initial commit for the gitpod config files are here?

**Comment by ghuntley** [comment]
Looks like I dorked, something up. Investigating.

**Comment by mpscholten** [comment]
Looks like it's fixed now :) Thanks!
